baseURL = "https://www.mrleong.net/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Hongster 鸿"
theme = "LoveIt"
enableEmoji = true
enableRobotsTXT = true

# LoveIt theme: https://bit.ly/3zk0aZh
[params]
  # LoveIt theme version
  version = "0.2.X"# site description
  description = "Hong's collection of random thoughts"
  # site keywords
  keywords = ["Personal", "Blog"]

  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "https://www.gravatar.com/avatar/7d37e5405950d1fac77cd499838beac5?s=192"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Hong's collection of random thoughts..."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Header config
  # 页面头部导航栏配置
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    # 页面头部导航栏标题配置
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      logo = ""
      # title name
      # 标题名称
      name = "Hongster's Random Thoughts"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = false

  [params.social]
    Email = "hong@mrleong.net"
    Github = "hongster"
    Instagram = "hongster85"
    Keybase = "hongster"
    Reddit = "hongster"
    Telegram = "hongster"

  # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2022
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>'

  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "UA-17448966-1"
      anonymizeIP = true

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "All blog posts"
    weight = 1
  [[menu.main]]
    identifier = "dancing"
    name = "Dancing"
    url = "/categories/dancing/"
    title = "Dancer life"
    weight = 2
  [[menu.main]]
    identifier = "johor food"
    name = "Johor Food"
    title = "Favorite food places in Johor"
    url = "/food/favorite-johor-food-places"
    weight = 3
  [[menu.main]]
    identifier = "kv food"
    name = "KV Food"
    title = "Favorite food places in Klang Valley"
    url = "/food/favorite-klang-valley-food-places"
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    title = "Tagged posts"
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true

# Author config
[author]
  name = "Hong"
  email = "hong@mrleong.net"
  link = ""