baseURL = "https://www.mrleong.net/"
title = "Hong 鸿"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Hong 鸿"
description = "Hong's personal blog"
keywords = [ "Blog", "Ballroom Dance", "Camping" ]
author = "Hong"
images = [ "https://www.gravatar.com/avatar/7d37e5405950d1fac77cd499838beac5?s=160&d=identicon" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "https://gravatar.com/avatar/681eebd3530e09d937013b86171324d27dd0ee1d837647803570f562290ddc37.png?s=32"
  favicon16x16 = "https://gravatar.com/avatar/681eebd3530e09d937013b86171324d27dd0ee1d837647803570f562290ddc37.png?s=16"
  favicon32x32 = "https://gravatar.com/avatar/681eebd3530e09d937013b86171324d27dd0ee1d837647803570f562290ddc37.png?s=32"
  apple_touch_icon = "https://gravatar.com/avatar/681eebd3530e09d937013b86171324d27dd0ee1d837647803570f562290ddc37.png?s=180"
  safari_pinned_tab = "https://gravatar.com/avatar/681eebd3530e09d937013b86171324d27dd0ee1d837647803570f562290ddc37.png?s=32"

  [params.label]
  text = "Home"
  icon = "https://www.gravatar.com/avatar/7d37e5405950d1fac77cd499838beac5?s=160&d=identicon"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Hong 鸿"
  subtitle = "Hong's personal blog"
  imageUrl = "https://www.gravatar.com/avatar/7d37e5405950d1fac77cd499838beac5?s=160&d=identicon"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "My image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://fosstodon.org/@hongster"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/hongster/"

[params.analytics.google]
SiteVerificationTag = "WilsEkq7VUHYdwiQ1CFM4H9M1JhNpUGEH4XjAHxVMzc"

#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

#[params.analytics.yandex]
#SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  #[params.editPost]
  #URL = "https://github.com/<path_to_repo>/content"
  #Text = "Suggest Changes"
  #appendFilePath = true

  # Fuzzy search. Need to add "search/" link to menu
  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "food-johor"
name = "Food:Johor"
url = "/food/favorite-johor-food-places/"
weight = 10

[[menu.main]]
identifier = "food-kv"
name = "Food:KV"
url = "/food/favorite-klang-valley-food-places/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.goldmark]
    [markup.goldmark.renderer]
            unsafe = true

  [markup.highlight]
    noClasses = false

[services]
  [services.googleAnalytics]
    ID = 'G-4YLRPM7MH2'